name: CI Pipeline
on: [push, pull_request, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - run: echo "Hello, World!"

        